# -*- coding: utf-8 -*-
"""Data Extractor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSOxyER8rYuu43rgbfgxogzN7nFjlOLE
"""

pip install openai

import os
import openai
import json

openai.api_key = os.getenv("OPENAI_API_KEY")

def extract_data_with_llm(input_text):
  prompt = f"""
You are a highly skilled data extraction tool.
Your task is to extract the name, email, and phone number from the given text.
You MUST respond with a valid JSON object.
The JSON object MUST have the following keys:
- `name`: The full name of the person.
- `email`: The email address of the person.
- `phone_number`: The phone number of the person.

Text to process:
{input_text}
"""
  try:
    response = openai.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt}
            ],
            temperature=0,
        )

    extracted_json_string = response.choices[0].message.content
    extracted_data = json.loads(extracted_json_string)

    return extracted_data

  except openai.APIError as e:
        print(f"An API error occurred: {e}")
        return None
  except json.JSONDecodeError as e:
        print(f"Failed to decode JSON from LLM response: {e}")
        print(f"LLM response was: {extracted_json_string}")
        return None

#Example Usage
messy_data = """
Hello, my name is **Priya Singh**. I am a software engineer.
You can email me at priya.singh@devcorp.net. If you want to talk, you can call me at +91-9988776655.
"""

structured_data = extract_data_with_llm(messy_data)

if structured_data:
  print("Data extracted succefully")
  print(json.dumps(structured_data, indent=2))

else:
  print("Data Extraction Failed")